// mcm-v2 — Proposal certificate parity. The downloadable pdf-lib certificate now
// mirrors the hosted web page section-for-section and is driven by the SAME pure
// bridge helper. Behavioral tests load the generated bytes and assert page count
// degrades honestly with the snapshot; a source-read proves single-source math
// and the web competitive-copy gate.
// TC-CM-01..04

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { PDFDocument } from 'pdf-lib'
import { generateProposalPdf } from '@/lib/pdf/proposal'
import { buildCalculatedAnalysis, buildPlaceholderAnalysis } from '@/lib/statement/analysis'

const baseParams = {
  companyName:  'Harbor Diner',
  contactName:  'Pat Smith',
  contactEmail: 'pat@harbor.example',
  calendlyLink: 'https://cal.example/321',
  generatedAt:  '2026-06-15T00:00:00Z',
}

describe('TC-CM-01: calculated analysis → multi-page certificate (proposal + intelligence)', () => {
  it('renders at least two pages and is a valid PDF', async () => {
    const analysis = buildCalculatedAnalysis({
      monthlyVolume:      100_000,
      currentMonthlyFees: 3_200,
      transactionCount:   2_000,
      companyName:        'Harbor Diner',
      statementPeriod:    'March 2026',
    })
    const bytes = await generateProposalPdf({ ...baseParams, analysis })
    expect(bytes).toBeInstanceOf(Uint8Array)
    expect(bytes.byteLength).toBeGreaterThan(0)

    const doc = await PDFDocument.load(bytes)
    expect(doc.getPageCount()).toBeGreaterThanOrEqual(2)
  })

  it('a calculated-but-zero-savings analysis still produces the intelligence page', async () => {
    // bridge is non-null (calculated, volume > 0) even when savings clamp to 0.
    const analysis = buildCalculatedAnalysis({
      monthlyVolume:      100_000,
      currentMonthlyFees: 1_000, // below proposed → savings 0
      transactionCount:   2_000,
    })
    const doc = await PDFDocument.load(await generateProposalPdf({ ...baseParams, analysis }))
    expect(doc.getPageCount()).toBeGreaterThanOrEqual(2)
  })
})

describe('TC-CM-02: placeholder analysis (bridge null) → single proposal page, no fabricated bridge', () => {
  it('still generates a valid PDF and omits the intelligence page', async () => {
    const analysis = buildPlaceholderAnalysis({ metadata: {}, source: 'web' }, 'statement.pdf', 'Acme')
    const bytes = await generateProposalPdf({ ...baseParams, companyName: 'Acme', analysis })
    expect(bytes.byteLength).toBeGreaterThan(0)

    const doc = await PDFDocument.load(bytes)
    expect(doc.getPageCount()).toBe(1)
  })
})

describe('TC-CM-03: single-source math + web honesty gate (source-read)', () => {
  const root = join(__dirname, '..')

  it('the PDF generator derives figures from the shared bridge helper', () => {
    const pdfSrc = readFileSync(join(root, 'lib', 'pdf', 'proposal.ts'), 'utf8')
    expect(pdfSrc).toContain('deriveCostSavingsBridge')
  })

  it('the web page gates the "already competitive" copy on calculated confidence', () => {
    const page = readFileSync(join(root, 'app', 'p', '[token]', 'page.tsx'), 'utf8')
    expect(page).toMatch(/already competitive/)
    expect(page).toMatch(/confidence === 'calculated'/)
  })
})
