// This file is auto-generated by Supabase CLI.
// Run: npx supabase gen types typescript --local > types/database.ts
// Placeholder stub until Supabase project is linked.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          industry_type: string | null
          status: string
          plan_id: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenants']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>
      }
      workspaces: {
        Row: {
          id: string
          tenant_id: string
          name: string
          slug: string
          is_default: boolean
          status: string
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['workspaces']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['workspaces']['Insert']>
      }
      memberships: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          user_id: string
          role_id: string
          status: string
          invited_by: string | null
          invited_at: string | null
          joined_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['memberships']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['memberships']['Insert']>
      }
      roles: {
        Row: {
          id: string
          tenant_id: string | null
          name: string
          slug: string
          description: string | null
          is_system: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['roles']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['roles']['Insert']>
      }
      companies: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          name: string
          domain: string | null
          phone: string | null
          website: string | null
          industry: string | null
          employee_count: number | null
          annual_revenue: number | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          zip: string | null
          country: string
          status: string
          source: string | null
          owner_id: string | null
          tags: string[] | null
          metadata: Json
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          workspace_id: string
          name: string
          domain?: string | null
          phone?: string | null
          website?: string | null
          industry?: string | null
          employee_count?: number | null
          annual_revenue?: number | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          country?: string
          status?: string
          source?: string | null
          owner_id?: string | null
          tags?: string[] | null
          metadata?: Json
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['companies']['Insert']>
      }
      contacts: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          company_id: string | null
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          title: string | null
          department: string | null
          is_primary_contact: boolean
          status: string
          source: string | null
          owner_id: string | null
          do_not_contact: boolean
          tags: string[] | null
          metadata: Json
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          workspace_id: string
          company_id?: string | null
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          title?: string | null
          department?: string | null
          is_primary_contact?: boolean
          status?: string
          source?: string | null
          owner_id?: string | null
          do_not_contact?: boolean
          tags?: string[] | null
          metadata?: Json
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['contacts']['Insert']>
      }
      leads: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          company_id: string | null
          contact_id: string | null
          name: string
          stage: string
          status: string
          source: string | null
          assigned_to: string | null
          priority: string
          estimated_value: number | null
          expected_close_date: string | null
          disqualification_reason: string | null
          converted_at: string | null
          converted_to_opportunity_id: string | null
          tags: string[] | null
          metadata: Json
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          workspace_id: string
          company_id?: string | null
          contact_id?: string | null
          name: string
          stage: string
          status?: string
          source?: string | null
          assigned_to?: string | null
          priority?: string
          estimated_value?: number | null
          expected_close_date?: string | null
          disqualification_reason?: string | null
          converted_at?: string | null
          converted_to_opportunity_id?: string | null
          tags?: string[] | null
          metadata?: Json
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['leads']['Insert']>
      }
      accounts: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          company_id: string | null
          name: string
          status: string
          account_type: string | null
          owner_id: string | null
          monthly_revenue: number | null
          contract_start_date: string | null
          contract_end_date: string | null
          renewal_date: string | null
          processor: string | null
          tags: string[] | null
          metadata: Json
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          workspace_id: string
          company_id?: string | null
          name: string
          status?: string
          account_type?: string | null
          owner_id?: string | null
          monthly_revenue?: number | null
          contract_start_date?: string | null
          contract_end_date?: string | null
          renewal_date?: string | null
          processor?: string | null
          tags?: string[] | null
          metadata?: Json
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['accounts']['Insert']>
      }
      opportunities: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          company_id: string | null
          account_id: string | null
          lead_id: string | null
          name: string
          stage: string
          status: string
          value: number | null
          probability: number | null
          expected_close_date: string | null
          closed_at: string | null
          lost_reason: string | null
          owner_id: string | null
          tags: string[] | null
          metadata: Json
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['opportunities']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['opportunities']['Insert']>
      }
      activities: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          activity_type: string
          subject: string | null
          body: string | null
          outcome: string | null
          occurred_at: string | null
          duration_minutes: number | null
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          account_id: string | null
          performed_by: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['activities']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['activities']['Insert']>
      }
      notes: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          body: string
          pinned: boolean
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          account_id: string | null
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['notes']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['notes']['Insert']>
      }
      tasks: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          title: string
          description: string | null
          status: string
          priority: string
          due_date: string | null
          completed_at: string | null
          assigned_to: string | null
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          account_id: string | null
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['tasks']['Insert']>
      }
      conversations: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string
          channel: string
          subject: string | null
          status: string
          direction: string | null
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          account_id: string | null
          assigned_to: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['conversations']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['conversations']['Insert']>
      }
      system_events: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          event_type: string
          event_version: string
          payload: Json
          source: string | null
          actor_id: string | null
          subject_type: string | null
          subject_id: string | null
          idempotency_key: string | null
          occurred_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['system_events']['Row'], 'id' | 'created_at' | 'occurred_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['system_events']['Insert']>
      }
      event_dispatch_queue: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          event_type: string
          payload: Json
          idempotency_key: string
          status: string
          dispatched_at: string | null
          attempts: number
          last_error: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['event_dispatch_queue']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['event_dispatch_queue']['Insert']>
      }
      workflow_runs: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          workflow_config_id: string | null
          trigger_event_id: string | null
          status: string
          subject_type: string | null
          subject_id: string | null
          started_at: string | null
          completed_at: string | null
          failed_at: string | null
          error_message: string | null
          context: Json
          metadata: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['workflow_runs']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['workflow_runs']['Insert']>
      }
      job_executions: {
        Row: {
          id: string
          tenant_id: string
          workflow_run_id: string | null
          job_type: string
          inngest_run_id: string | null
          status: string
          attempt: number
          input: Json
          output: Json
          error_message: string | null
          started_at: string | null
          completed_at: string | null
          failed_at: string | null
          duration_ms: number | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['job_executions']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['job_executions']['Insert']>
      }
      approval_requests: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          workflow_run_id: string | null
          job_execution_id: string | null
          request_type: string
          status: string
          requested_by_system: boolean
          assignee_id: string | null
          subject_type: string | null
          subject_id: string | null
          payload: Json
          decision: Json
          approved_by: string | null
          decided_at: string | null
          expires_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['approval_requests']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['approval_requests']['Insert']>
      }
      webhook_events: {
        Row: {
          id: string
          tenant_id: string | null
          source: string
          event_type: string | null
          headers: Json
          payload: Json
          processed: boolean
          processed_at: string | null
          error_message: string | null
          received_at: string
        }
        Insert: Omit<Database['public']['Tables']['webhook_events']['Row'], 'id' | 'received_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['webhook_events']['Insert']>
      }
      automation_failures: {
        Row: {
          id: string
          tenant_id: string
          workflow_run_id: string | null
          job_execution_id: string | null
          failure_type: string
          error_code: string | null
          error_message: string | null
          stack_trace: string | null
          context: Json
          resolved: boolean
          resolved_by: string | null
          resolved_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['automation_failures']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['automation_failures']['Insert']>
      }
      notification_queue: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          recipient_id: string
          channel: string
          notification_type: string
          title: string | null
          body: string | null
          link: string | null
          read_at: string | null
          sent_at: string | null
          status: string
          metadata: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['notification_queue']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['notification_queue']['Insert']>
      }
      industry_profiles: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          pipeline_defaults: Json
          scoring_defaults: Json
          workflow_defaults: Json
          prompt_defaults: Json
          feature_defaults: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['industry_profiles']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['industry_profiles']['Insert']>
      }
      pipeline_stage_configs: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          pipeline_type: string
          slug: string
          name: string
          position: number
          color: string | null
          is_terminal: boolean
          terminal_outcome: string | null
          entry_conditions: Json
          exit_conditions: Json
          industry_profile_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['pipeline_stage_configs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['pipeline_stage_configs']['Insert']>
      }
      prompt_configs: {
        Row: {
          id: string
          tenant_id: string | null
          workspace_id: string | null
          slug: string
          name: string
          description: string | null
          module: string
          purpose: string
          is_active: boolean
          active_version_id: string | null
          industry_profile_id: string | null
          metadata: Json
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['prompt_configs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['prompt_configs']['Insert']>
      }
      prompt_versions: {
        Row: {
          id: string
          tenant_id: string | null
          prompt_config_id: string
          version: number
          system_prompt: string
          user_prompt_template: string
          model: string
          temperature: number
          max_tokens: number
          variables: Json
          change_notes: string | null
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['prompt_versions']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['prompt_versions']['Insert']>
      }
      scoring_configs: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          slug: string
          name: string
          score_type: string
          subject_type: string
          dimensions: Json
          thresholds: Json
          prompt_config_id: string | null
          is_active: boolean
          industry_profile_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['scoring_configs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['scoring_configs']['Insert']>
      }
      workflow_configs: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          slug: string
          name: string
          trigger_event: string
          steps: Json
          conditions: Json
          is_active: boolean
          requires_approval: boolean
          industry_profile_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['workflow_configs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['workflow_configs']['Insert']>
      }
      policy_rules: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          slug: string
          name: string
          module: string
          rule_type: string
          conditions: Json
          actions: Json
          is_active: boolean
          priority: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['policy_rules']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['policy_rules']['Insert']>
      }
      dashboard_configs: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          slug: string
          name: string
          layout: Json
          filters: Json
          is_default: boolean
          is_shared: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['dashboard_configs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['dashboard_configs']['Insert']>
      }
      fit_scores: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          subject_type: string
          subject_id: string
          score: number
          score_version: string
          scoring_config_id: string | null
          dimensions: Json
          reasoning: string | null
          model_used: string | null
          confidence: number | null
          is_current: boolean
          generated_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['fit_scores']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['fit_scores']['Insert']>
      }
      urgency_scores: { Row: Database['public']['Tables']['fit_scores']['Row']; Insert: Database['public']['Tables']['fit_scores']['Insert']; Update: Database['public']['Tables']['fit_scores']['Update'] }
      engagement_scores: { Row: Database['public']['Tables']['fit_scores']['Row']; Insert: Database['public']['Tables']['fit_scores']['Insert']; Update: Database['public']['Tables']['fit_scores']['Update'] }
      opportunity_scores: { Row: Database['public']['Tables']['fit_scores']['Row']; Insert: Database['public']['Tables']['fit_scores']['Insert']; Update: Database['public']['Tables']['fit_scores']['Update'] }
      health_scores: { Row: Database['public']['Tables']['fit_scores']['Row']; Insert: Database['public']['Tables']['fit_scores']['Insert']; Update: Database['public']['Tables']['fit_scores']['Update'] }
      churn_risk_scores: { Row: Database['public']['Tables']['fit_scores']['Row']; Insert: Database['public']['Tables']['fit_scores']['Insert']; Update: Database['public']['Tables']['fit_scores']['Update'] }
      agent_recommendations: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          subject_type: string
          subject_id: string
          recommendation_type: string
          title: string
          body: string | null
          priority: string
          status: string
          workflow_run_id: string | null
          prompt_config_id: string | null
          raw_output: Json
          accepted_by: string | null
          accepted_at: string | null
          rejected_by: string | null
          rejected_at: string | null
          expires_at: string | null
          metadata: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['agent_recommendations']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['agent_recommendations']['Insert']>
      }
      recommendation_feedback: {
        Row: {
          id: string
          tenant_id: string
          recommendation_id: string
          user_id: string
          rating: number | null
          useful: boolean | null
          comment: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['recommendation_feedback']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['recommendation_feedback']['Insert']>
      }
      artifacts: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          name: string
          artifact_type: string
          mime_type: string | null
          file_size_bytes: number | null
          storage_path: string | null
          storage_bucket: string
          status: string
          is_latest: boolean
          current_version_id: string | null
          subject_type: string | null
          subject_id: string | null
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          account_id: string | null
          description: string | null
          tags: string[] | null
          metadata: Json
          uploaded_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['artifacts']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['artifacts']['Insert']>
      }
      artifact_versions: {
        Row: {
          id: string
          tenant_id: string
          artifact_id: string
          version_number: number
          storage_path: string
          storage_bucket: string
          file_size_bytes: number | null
          mime_type: string | null
          change_notes: string | null
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['artifact_versions']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['artifact_versions']['Insert']>
      }
      artifact_links: {
        Row: {
          id: string
          tenant_id: string
          artifact_id: string
          link_type: string
          link_id: string
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['artifact_links']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['artifact_links']['Insert']>
      }
      evidence_records: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          subject_type: string
          subject_id: string
          evidence_type: string
          source_type: string | null
          source_id: string | null
          artifact_id: string | null
          field_path: string | null
          value_snapshot: Json | null
          weight: number | null
          notes: string | null
          workflow_run_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['evidence_records']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['evidence_records']['Insert']>
      }
      document_extractions: {
        Row: {
          id: string
          tenant_id: string
          artifact_id: string
          artifact_version_id: string | null
          extraction_type: string
          status: string
          raw_text: string | null
          structured_data: Json
          model_used: string | null
          error_message: string | null
          processed_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['document_extractions']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['document_extractions']['Insert']>
      }
      sender_identities: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          name: string
          email: string
          reply_to: string | null
          domain_settings_id: string | null
          is_verified: boolean
          is_default: boolean
          status: string
          resend_identity_id: string | null
          metadata: Json
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['sender_identities']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['sender_identities']['Insert']>
      }
      domain_settings: {
        Row: {
          id: string
          tenant_id: string
          domain: string
          is_verified: boolean
          verification_token: string | null
          dns_records: Json
          resend_domain_id: string | null
          status: string
          verified_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['domain_settings']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['domain_settings']['Insert']>
      }
      email_templates: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          name: string
          slug: string
          subject_template: string
          body_html_template: string | null
          body_text_template: string | null
          template_type: string
          variables: Json
          is_active: boolean
          industry_profile_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['email_templates']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['email_templates']['Insert']>
      }
      email_drafts: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          sender_identity_id: string | null
          template_id: string | null
          to_email: string
          to_name: string | null
          cc_emails: string[] | null
          bcc_emails: string[] | null
          subject: string
          body_html: string | null
          body_text: string | null
          status: string
          subject_type: string | null
          subject_id: string | null
          company_id: string | null
          contact_id: string | null
          lead_id: string | null
          opportunity_id: string | null
          workflow_run_id: string | null
          approval_request_id: string | null
          prompt_config_id: string | null
          generated_by_ai: boolean
          ai_generation_metadata: Json
          approved_at: string | null
          approved_by: string | null
          rejected_at: string | null
          superseded_at: string | null
          sent_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['email_drafts']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['email_drafts']['Insert']>
      }
      email_sends: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          draft_id: string | null
          sender_identity_id: string | null
          to_email: string
          subject: string
          resend_message_id: string | null
          status: string
          sent_at: string | null
          contact_id: string | null
          company_id: string | null
          error_message: string | null
          metadata: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['email_sends']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['email_sends']['Insert']>
      }
      email_events: {
        Row: {
          id: string
          tenant_id: string | null
          email_send_id: string | null
          resend_message_id: string | null
          event_type: string
          occurred_at: string
          payload: Json
          provider_event_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['email_events']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['email_events']['Insert']>
      }
      unsubscribes: {
        Row: {
          id: string
          tenant_id: string
          email: string
          reason: string | null
          unsubscribed_at: string
          source: string | null
          email_send_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['unsubscribes']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['unsubscribes']['Insert']>
      }
      suppression_rules: {
        Row: {
          id: string
          tenant_id: string
          rule_type: string
          value: string
          reason: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['suppression_rules']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['suppression_rules']['Insert']>
      }
      permissions: {
        Row: {
          id: string
          slug: string
          description: string | null
          module: string
        }
        Insert: Omit<Database['public']['Tables']['permissions']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['permissions']['Insert']>
      }
      role_permissions: {
        Row: {
          role_id: string
          permission_id: string
        }
        Insert: Database['public']['Tables']['role_permissions']['Row']
        Update: Partial<Database['public']['Tables']['role_permissions']['Row']>
      }
      feature_entitlements: {
        Row: {
          id: string
          tenant_id: string
          feature_slug: string
          enabled: boolean
          config: Json
          expires_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['feature_entitlements']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['feature_entitlements']['Insert']>
      }
      branding_profiles: {
        Row: {
          id: string
          tenant_id: string
          workspace_id: string | null
          logo_url: string | null
          favicon_url: string | null
          primary_color: string | null
          secondary_color: string | null
          accent_color: string | null
          font_family: string | null
          custom_css: string | null
          app_name: string | null
          support_email: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['branding_profiles']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['branding_profiles']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      upsert_current_score: {
        Args: {
          p_table: string
          p_tenant_id: string
          p_workspace_id: string | null
          p_subject_type: string
          p_subject_id: string
          p_score: number
          p_score_version?: string
          p_scoring_config_id?: string | null
          p_dimensions?: Json
          p_reasoning?: string
          p_model_used?: string
          p_confidence?: number
        }
        Returns: Json  // row_to_json of the inserted score row
      }
    }
    Enums: Record<string, never>
  }
}
