-- =============================================================================
-- MCM v2 — Hosted Proposal Web Page (Slice A, #37)
-- Migration: 20240056
-- Purely additive to proposal_events. Enables a public, tokenized hosted
-- proposal page at /p/{share_token}.
--   - share_token: unguessable url-safe token for the public page (unique).
--   - metadata:    immutable StatementAnalysis snapshot + certificate artifact id,
--                  so the public page is a single read that never drifts.
--   - proposal_status gains 'draft' (a generated, not-yet-sent hosted proposal).
--   - capture_source gains 'savings_analysis' (generated by the savings flow).
-- No existing columns dropped or renamed.
-- =============================================================================

ALTER TABLE proposal_events
  ADD COLUMN IF NOT EXISTS share_token text,
  ADD COLUMN IF NOT EXISTS metadata    jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Widen proposal_status to allow 'draft' (generated hosted proposal, pre-send).
ALTER TABLE proposal_events
  DROP CONSTRAINT IF EXISTS proposal_events_proposal_status_check;
ALTER TABLE proposal_events
  ADD CONSTRAINT proposal_events_proposal_status_check
    CHECK (proposal_status IN ('draft','sent','viewed','accepted','rejected','expired','withdrawn'));

-- Widen capture_source to record the savings-analysis generator as provenance.
ALTER TABLE proposal_events
  DROP CONSTRAINT IF EXISTS proposal_events_capture_source_check;
ALTER TABLE proposal_events
  ADD CONSTRAINT proposal_events_capture_source_check
    CHECK (capture_source IN ('manual','bcc_ingest','forward_ingest','outlook_sync','api','savings_analysis'));

-- Unguessable public lookup key — unique across all rows that have one.
CREATE UNIQUE INDEX IF NOT EXISTS idx_proposal_events_share_token
  ON proposal_events (share_token)
  WHERE share_token IS NOT NULL;
